chore: relax dependency on httpx
V-Mann-Nick/keycloak-admin-aio pull request #17
Opened 2024-10-09 12:14 UTC by tadeusz-delphai

This change allows using `keycloak-admin-aio` with versions of `httpx` newer than [0.23.3](https://github.com/encode/httpx/releases/tag/0.23.30), which was originally released in early 2023.

Unit tests still pass:
```
$ poetry run pytest 
======================================== test session starts ========================================
platform linux -- Python 3.9.19, pytest-7.4.4, pluggy-1.5.0
Keycloak version: latest
rootdir: /home/tadeusz/delphai/keycloak-admin-aio
configfile: pyproject.toml
plugins: anyio-4.6.0, asyncio-0.21.2
asyncio: mode=auto
collected 68 items                                                                                  

test/test_admin_events.py .                                                                   [  1%]
test/test_groups.py ........                                                                  [ 13%]
test/test_roles.py ...............                                                            [ 35%]
test/test_users.py ........s.....s...                                                         [ 61%]
test/test_attack_detection.py ...                                                             [ 66%]
test/test_authentication.py .                                                                 [ 67%]
test/test_client_scopes.py ........s.                                                         [ 82%]
test/test_clients.py .......s..                                                               [ 97%]
test/test_keycloak_admin_aio.py .                                                             [ 98%]
test/test_sessions.py .                                                                       [100%]

============================= 64 passed, 4 skipped in 63.00s (0:01:03) ==============================

```

2024-10-10 20:43 UTC, V-Mann-Nick reviewed
Thanks for your interest. 

I think there's might be some misunderstanding on the version constraint here. Currently the project specifies `httpx@^0.23.3`. This means that `>=0.23.3 <1.0.0` is the version range. Seeing that `httpx` latest version is currently at `0.27.2` all newer versions are included. The `poetry.lock` in this project is not relevant for library consumers and only important for development dependencies.

In this light the proposed change I believe does not actually change anything for consumer projects.

That being said I do not believe the current version constraint is the best. I believe a better version constraint might be `>=0.23.3`. Of course this would mean that if `httpx@>=1.0.0` has a relevant breaking change this might break projects, but one could argue that it might be better to assume that it wouldn't break until proven otherwise to not block consumers from updating. Furthermore the lower bound of `httpx` could be tweaked as well, but I haven't actually tested lower versions.

I haven't been developing Python in a while so there might be something crucial I'm missing here 🤔. In this case I apologize, and would very much appreciate if you could explain why this version constraint update is necessary.

Thanks a lot for your interest and I'm happy to review/merge any other contributions.

2024-10-10 20:55 UTC, anton-ryzhov commented
@V-Mann-Nick , thanks for reviewing.

The thing is that `poetry` handles versions with leading zeros [differently](https://python-poetry.org/docs/dependency-specification/#caret-requirements):
`^1.2` means `>=1.2.0 <2.0.0` as expected, but `^0.2.3` surprisingly means `>=0.2.3 <0.3.0`.

So `^0.23.3` defined here means `>=0.23.3, <0.24`, the version released 1.5 years ago

2024-10-10 21:43 UTC, V-Mann-Nick requested changes
Thank you @anton-ryzhov for clarifying this detail of semvar that I didn't know about. Of course this change request makes much more sense now 🙏

> @V-Mann-Nick , thanks for reviewing.
> 
> The thing is that `poetry` handles versions with leading zeros [differently](https://python-poetry.org/docs/dependency-specification/#caret-requirements): `^1.2` means `>=1.2.0 <2.0.0` as expected, but `^0.2.3` surprisingly means `>=0.2.3 <0.3.0`.
> 
> So `^0.23.3` defined here means `>=0.23.3, <0.24`, the version released 1.5 years ago

2024-10-10 21:43 UTC, V-Mann-Nick commented on poetry.lock
For the purpose of updating `httpx` for library consumers and update to the lockfile is not necessary.

2024-10-10 21:43 UTC, V-Mann-Nick commented on pyproject.toml
> +httpx = ">=0.23.3 <4"
```suggestion
httpx = ">=0.23.3"
```

Just wondering why not this?

2024-10-11 18:58 UTC, tadeusz-delphai commented on pyproject.toml
> +httpx = ">=0.23.3 <4"
That was a typo on my part, I wanted to say `<1`, not `<4`.

I updated the proposed change so that it doesn't include an upper limit.

2024-10-11 18:59 UTC, tadeusz-delphai commented on poetry.lock
I reverted the lockfile

2024-10-12 09:39 UTC, V-Mann-Nick approved these changes
Thanks very much for your contribution.

2024-10-12 09:39 UTC, merged